apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingres
  namespace: calculator
  annotations:
   # Use Traefik as the Ingress controller
    traefik.enable: "true" # Ensure Traefik picks up this Ingress
spec:
  ingressClassName: traefik
  rules:
  - host: akhil.local.com # Replace with your desired hostname
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-app-service
            port:
              number: 80
